import { MyNavbar } from "@/components/My_navbar"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
  
export default function GeneralLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return(
    <div className="px-36 py-10">
     <MyNavbar/>
            {children}
    </div>
)
  }




