// Generated by https://quicktype.io

export interface ITramosResponse {
    statusCode:    number;
    isExitoso:     boolean;
    errorMessages: null;
    resultado:     ResultadoTramos[];
}

export interface ResultadoTramos {
    idTramo:     number;
    idCarretera: number;
    nombre:      string;
    tipoTramos:  string;
    latitud:     number;
    longitud:    number;
    estado:      string;
}
// Generated by https://quicktype.io

export interface IResponseTramoIndiviual {
    statusCode:    number;
    isExitoso:     boolean;
    errorMessages: null;
    resultado:     ResultadoTramos;
}
