// Generated by https://quicktype.io

export interface ITipoDeViaResponse {
    statusCode:    number;
    isExitoso:     boolean;
    errorMessages: null;
    resultado:     ResultadoBase[];
}

export interface ResultadoBase {
    idTipoVia:          number;
    tipoDeVia:          string;
    fechaCreacion:      null | string;
    fechaActualizacion: string;
    carreteras:         any[];
}
// Generated by https://quicktype.io

export interface IGetTipoDeViaResponse {
    statusCode:    number;
    isExitoso:     boolean;
    errorMessages: null;
    resultado:     ResultadoID;
}

export interface ResultadoID {
    idTipoVia: number;
    tipoDeVia: string;
}


// Generated by https://quicktype.io

export interface IServicioResponse {
    statusCode:    number;
    isExitoso:     boolean;
    errorMessages: null;
    resultado:     ResultadoServicio[];
}

export interface ResultadoServicio {
    idUbicacion:   number;
    tipoServicios: string;
    latitud:       number;
    estado:        string;
}

